import { registerStyle } from '../../../../base/app/utils/styles'

// MNC page-level presets (the few things the layout primitives do not cover).
registerStyle('map-blur', 'blur-md', 'Blur the map behind the welcome modal')
registerStyle('dimmer', 'absolute inset-0 z-40 bg-black bg-opacity-50', 'Dim everything behind the welcome modal')
registerStyle('page-shell', 'relative', 'Positioned page wrapper for a full-screen map')
registerStyle('admin-page', 'min-h-dvh bg-gray-50 dark:bg-zinc-950', 'Account-management page background')
registerStyle('admin-container', 'mx-auto max-w-3xl px-4 py-8 sm:py-12', 'Centered column of the admin page')
registerStyle('about-page', 'mb-24 leading-relaxed', 'About page body')
registerStyle('about-block', 'mx-auto mt-40 w-full max-w-[1100px] px-7', 'First about block under the floating header')
registerStyle('about-section', 'mx-auto w-full max-w-[1100px] px-7', 'About content block with the page gutter')
registerStyle('about-split', 'mx-auto w-full max-w-[1100px] px-7 md:flex md:gap-12', 'Heading beside text on wide screens')
registerStyle('about-heading', 'mb-4 shrink-0 md:w-64', 'Fixed-width heading column of a split block')
registerStyle('eyebrow', 'text-sm font-medium uppercase tracking-widest text-teal-600', 'Small uppercase label above a title')
registerStyle('theme-card', 'rounded-2xl border border-zinc-200 p-6 dark:border-zinc-700', 'About page theme card')
registerStyle('theme-icon', 'mb-3 h-7 w-7 text-teal-600', 'Icon on a theme card')
registerStyle('pill-button', 'rounded-full px-6 py-3 hover:bg-gray-300 hover:text-black dark:hover:bg-zinc-700 dark:hover:text-white', 'Rounded call-to-action button')
registerStyle('divider-wide', 'mb-12 mt-20', 'Divider between about sections')
registerStyle('moderate-trigger', 'fixed bottom-28 left-4 z-40 sm:bottom-6 sm:left-6 safe-bottom', 'Moderator button anchored bottom-left')
registerStyle('upload-float', 'fixed right-5 top-5 z-[60]', 'Floating upload widget (desktop)')
registerStyle('upload-float-mobile', 'pointer-events-auto fixed left-1/2 top-20 z-[60] -translate-x-1/2', 'Floating upload widget (mobile)')
registerStyle('pick-banner', 'fixed left-1/2 top-24 z-[60] flex -translate-x-1/2 items-center gap-3 rounded-full border-2 border-[#FB6D6D] bg-white px-5 py-2.5 shadow-lg dark:bg-black', '"Tap the map to drop your pin" banner')
registerStyle('pick-icon', 'h-5 w-5 text-[#FB6D6D]', 'Pin icon in the pick banner')
registerStyle('round-shadow', 'rounded-full shadow-lg', 'Floating round button')
