// Global "Learn More" label dictionary per language (generated by
// functions/backfill.mjs; empty until it has been run).
import linkLabelDict from '../../content/mncLinks.i18n.json'
// Display labels for the primary tags, keyed by the English data key.
import tagLabelDict from '../../content/mncTags.i18n.json'

/**
 * Reads an entry's text in the current UI language from its stored `i18n` map
 * (written once at entry creation — see functions/), falling back to the
 * original text when the locale or field has no translation.
 */
export function useLocalizedEntry() {
  const { locale } = useI18n()

  function lf(properties: any, field: 'title' | 'shortDesc' | 'description' | 'mncConnection' | 'location', fallback = ''): string {
    return properties?.i18n?.[locale.value]?.[field] || fallback
  }

  /** Translated label for a "Learn More" link (falls back to the original). */
  function linkLabel(label: string): string {
    return (linkLabelDict as any)[locale.value]?.[label] || label
  }

  /**
   * Display label for a primary tag. The tag stays the English data key
   * everywhere it is stored, filtered or compared — this is only what the user
   * reads. User-created tags have no translation and fall back to the key.
   */
  function tagLabel(tag: string | undefined | null): string {
    const key = (tag || '').trim()
    return (tagLabelDict as any)[locale.value]?.[key] || key
  }

  return { lf, linkLabel, tagLabel }
}
