// Global "Learn More" label dictionary per language (generated by
// functions/backfill.mjs; empty until it has been run).
import linkLabelDict from '../../content/mncLinks.i18n.json'

/**
 * Reads an entry's text in the current UI language from its stored `i18n` map
 * (written once at entry creation — see functions/), falling back to the
 * original text when the locale or field has no translation.
 */
export function useLocalizedEntry() {
  const { locale } = useI18n()

  function lf(properties: any, field: 'title' | 'shortDesc' | 'description' | 'mncConnection' | 'location', fallback = ''): string {
    return properties?.i18n?.[locale.value]?.[field] || fallback
  }

  /** Translated label for a "Learn More" link (falls back to the original). */
  function linkLabel(label: string): string {
    return (linkLabelDict as any)[locale.value]?.[label] || label
  }

  return { lf, linkLabel }
}
